\section{\ExercisePrefixObjectOrientation Exceptions}
Ähnlich wie in Java können Fehler während der Programmlaufzeit in C++ mittels Exceptions signalisiert werden.

\cpppInputListing{03_oo/problems/listings/exceptions_intro.cpp}

Es gibt jedoch einige Unterschiede zur Fehlerbehandlung in Java.
Das aus Java bekannte \lstinline{finally}-Konstrukt existiert in C++ nicht.
Außerdem kann jede Art von Wert geworfen werden -- sowohl Objekte als auch primitive Werte wie z.B. \lstinline{int}.
In der Praxis wird es jedoch empfohlen, den geworfenen Wert von \lstinline{std::exception} abzuleiten oder eine der existierenden Klassen aus der Standardbibliothek zu nutzen.

Im Gegensatz zu Java kann man Objekte nicht nur \emph{by-Reference} sondern auch \emph{by-Value} werfen und fangen.
In diesem Fall wird das geworfene Objekt nach der Behandlung im \lstinline{catch}-Block automatisch zerstört.
Wenn es \emph{by-Value} gefangen wird, wird das geworfene Objekt kopiert, ähnlich wie bei einem Funktionsaufruf.
Beispiel:

\cpppInputListing{03_oo/problems/listings/exceptions_by_what.cpp}

In der Praxis hat es sich durchgesetzt, \emph{by-Value} zu werfen und \emph{by-const-Reference} zu fangen.

\subsection{Implementierung einer Dummy-Klasse}
Erstelle eine Klasse \lstinline{C} und implementiere einen Konstruktor, einen Copy-Konstruktor und einen Destruktor.
Versehe diese mit Ausgaben auf der Konsole, so dass der Lebenszyklus während der Ausführung ersichtlich wird.

\subsection{}
Experimentiere mit Exceptions.
Probiere insbesondere die beiden o.g. Fälle aus und beobachte die Ausgabe.
Wann wird ein Objekt erstellt/kopiert/gelöscht?
Teste auch, was passiert, wenn du mehrere \lstinline{catch}-Blöcke erstellst und sich diese nur in der Übergabe unterscheiden (Wert/Referenz).

\cpppInputListing{03_oo/problems/listings/exceptions_multiple_catch.cpp}

Welcher \lstinline{catch} Block wird aufgerufen?
Spielt die Reihenfolge eine Rolle?

\subsection{Erweitern der Klasse \lstinline{List}}
\label{subsec:list_exceptions}
Füge der Klasse \lstinline{List} vom Vortag (\ref{sec:linked_list}) Bereichsprüfungen hinzu.
Schreibe die Methoden \lstinline{insertElementAt()}, \lstinline{getNthElement()} und \lstinline{deleteAt()} so um, dass eine Exception geworfen wird, falls der angegebene Index die Größe der Liste überschreitet.
Verwende als Exception die Klasse \lstinline{std::out_of_range}\footnote{\url{http://en.cppreference.com/w/cpp/error/out_of_range}} aus dem \lstinline{stdexcept} Header.

\hints{
    \item Du musst hierbei keinerlei \lstinline{try/catch} Block verwenden, da es rein um das werfen einer Exception geht.
}

\subsection{Testen der Implementierung}
Teste die erweiterte Implementierung der Klasse List.
Provoziere eine Exception, indem du falsche Indices angibst, und fange die Exception als \lstinline{const} Referenz mit einem \lstinline{catch} Block ab (s.o.).
Du kannst die Methode \lstinline{what()}\footnote{\url{http://en.cppreference.com/w/cpp/error/exception/what}} benutzen, um an den Nachrichtentext der Exception zu gelangen.
